{% set name = "pyspatialstats" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyspatialstats-{{ version }}.tar.gz
  sha256: 52b1dd54ee776f4bc486e15ffb8537bd7b1251527165362438fccb7f430547e1

build:
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0
  skip: true  # [py<310 or python_impl=="pypy"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - numpy >=2.2.1
  host:
    - python
    - setuptools
    - wheel
    - numpy >=2.2.1
    - cython >=3.0
    - scipy
    - pip
  run:
    - python
    - joblib
    - pandas
    - scipy
    - numpy

test:
  imports:
    - pyspatialstats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jasperroebroek/pyspatialstats
  license: MIT
  license_file: LICENSE
  summary: Spatial statistics for Python
  doc_url: https://focal-stats.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/jasperroebroek/pyspatialstats

extra:
  recipe-maintainers:
    - jasperroebroek
