{% set name = "pyspatialstats" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyspatialstats-{{ version }}.tar.gz
  sha256: d7a224fab537e7ac30dd225d2de9d6f713812956f9fe989f236fb4de12c1e718

build:
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - numpy >=2.2.1
  host:
    - python
    - setuptools
    - wheel
    - numpy >=2.2.1
    - cython >=3.0
    - scipy
    - pip
  run:
    - python
    - joblib
    - pandas
    - scipy
    - numpy

test:
  imports:
    - pyspatialstats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jasperroebroek/pyspatialstats
  license: MIT
  license_file: LICENSE
  summary: Spatial statistics for Python
  doc_url: https://pyspatialstats.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/jasperroebroek/pyspatialstats

extra:
  recipe-maintainers:
    - jasperroebroek
